### ISSUE TITLE
Specifying AWS lambda layer arn with --layer-arn flag in newrelic-lambda layers install command does not work

### ISSUE THREAD

**Issue by shouryaveer-codal** [newrelic/newrelic-lambda-cli#190] opened 2021-12-07 06:55 UTC
## I have multiple layers added for a python3.8 runtime and when I try specifying a specific layer arn in newrelic-lambda layers install command with `--layer-arn` flag as suggested in docs like this: 
`newrelic-lambda layers install -f <lambda_name> --nr-account-id <NRACCOUNTID> --layer-arn <arn:xxx> --upgrade`
It gives following type of Parameter Validation Error:
`Error: Unexpected AWS error: Parameter validation failed:
Invalid type for parameter Layers[0], value: ['arn:xxx'], type: <class 'list'>, valid types: <class 'str'>
`

**Comment by ysolis** [comment] 2021-12-13 14:58
i have similar problem but only happens when i am running in AWS CodeCommit, if i run manually the command in my shell, this works normally.

I think the problem is related with the Python `click` library (CLI args).

**Comment by sbutlernimble** [comment] 2021-12-15 05:20
I am getting the exact same error when this command is being run in Travis for a node project running in node 14:

Error: Unexpected AWS error: Parameter validation failed:
Invalid type for parameter Layers[0], value: ['arn:****'], type: <class 'list'>, valid types: <class 'str'>

Command being run is:
newrelic-lambda layers install -u --function lambdaFuncName --layer-arn "arn:****"

**Comment by sbutlernimble** [comment] 2021-12-15 06:04
It seems there is a fix for this, it is just not released yet:
https://github.com/newrelic/newrelic-lambda-cli/pull/191

I will therefore wait with bated breath for this fix to actually be released.

**Comment by kolanos** [comment] 2021-12-16 15:51
This fix was included in `v0.6.8`. Apologies for the delay.

**Closed by kolanos** 2021-12-16 15:51 UTC
Labels: bug
